### ISSUE TITLE
Secrets are requested every hour, even without a request happening

### ISSUE THREAD

**Issue by JeroenVdb** [benvp/insomnia-plugin-op#1]
First of all: loving the neet plugin, works great!

A minor discomfort for me is that when Insomnia is open, but idle in the background, I will get requested access to 1Password secrets every hour.

I guess this happens because the cache expired and Insomnia is doing something in the background that needs the environments. Is this something you have an impact on to fix?

**Comment by JeroenVdb** [comment]
Never mind, I guess I have found the culprit and you can't probably do much about it. Every minute there is a syncing mechanism that needs all the data, including environmental data.

https://github.com/Kong/insomnia/blob/75c6a94ae99f9cfbbba8da0e817228e75454d03e/packages/insomnia/src/ui/components/dropdowns/sync-dropdown.tsx#L55-L60

I'ml going to ask Insomnia why the 1Password plugin tag is executed because I guess only the tag itself needs to be synced and not the value itself.

**Comment by JeroenVdb** [comment]
Created issue here: https://github.com/Kong/insomnia/issues/7260

**Comment by benvp** [comment]
Thanks for opening that up on the insomnia repo. That's one of the reasons I implemented a caching because it kept constantly asking me. In addition, requesting the data via the op plugin takes time and causes Insomnia to lag while requesting the secrets from the vault.

There are quite a few events when this happens, like opening the variables screen, selecting a variable, changing it. IIRC even just focussing the window does a refresh of the variables.

Maybe, as a workaround we can introduce a setting to set the cache ttl. With a long ttl it would require a restart of insomnia if one of the passwords would be changed, though.
